---
# tasks file for Update-RPI

- user: name=pi password={{password}} 
  sudo: yes

- name: update software 
  apt:
   update_cache: true
   cache_valid_time: 3600

- name: Update all package to the latest version
  apt:
   upgrade: dist

- name: copy fichier sur le serveur dans /tmp
  copy:
          src: validation.txt
          dest: /tmp/validation.txt

  
...
